
library(cluster)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(highcharter)
library(knitr)
library(lubridate)
library(plyr)
library(rmarkdown)
library(sp)
library(stats)
library(stringi)
library(tidyr)
library(xts)